mode = "predict"

[project] 
name = "Project Name"
description = "Project Description"
version = "Project Version"
company = ""
author = "Author Name"

[logger]
filepath="./logs/project_name.log"
rotation="50MB"

[inference]
weights = "models/yolo26n.pt"
conf = 0.25
device = 0
imgsz = 1280


[camera]
source = "/home/emre/Desktop/workplace/yolo-pipeline/test_videos/2mintest.mp4"
width = 640
height = 480
delay = 30